import type { Metadata } from "next";
import '@/styles/globals.css'

// COMPONENTS
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className="">
        <Header />
        <main className="xl:flex-all-center">
          {children}
        </main>
      </body>
    </html>
  );
}
